name: "\U0001F41B Bug Report"
description: Report a bug in LangGraph. To report a security issue, please instead use the security option below. For questions, please use the GitHub Discussions.
labels: ["02 Bug Report"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. 
        
        Use this to report BUGS in LangChain. For usage questions, feature requests and general design questions, please use [GitHub Discussions](https://github.com/langchain-ai/langchain/discussions).
        
        If you're not certain that your issue is due to a bug in LangChain, please use [GitHub Discussions](https://github.com/langchain-ai/langchain/discussions)
        to ask for help with your issue.
        
        Relevant links to check before filing a bug report to see if your issue has already been reported, fixed or
        if there's another way to solve your problem:
        
        [LangChain Github Discussions](https://github.com/langchain-ai/langgraph/discussions),
        [LangChain Github Issues](https://github.com/langchain-ai/langgraph/issues),
        [LangGraph documentation](https://langchain-ai.github.io/langgraph/).
        [LangChain documentation with the integrated search](https://python.langchain.com/docs/get_started/introduction),
        [GitHub search](https://github.com/langchain-ai/langgraph),
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Before submitting this issue, please confirm that you have completed all the steps below by checking each option. These steps help ensure your issue is well-defined, relevant, and actionable.
      options:
        - label: I am filing a BUG! This is not a usage question which should be in [GitHub Discussions](https://github.com/langchain-ai/langgraph/discussions/new/choose).
          required: true
        - label: I am filing a BUG or a FEATURE REQUEST, not a usage question. (For questions, please use GitHub Discussions -- https://stackoverflow.com/help/minimal-reproducible-example)
          required: true
        - label: I added a clear and detailed title that summarizes the issue.
          required: true
        - label: I included a self-contained, minimal example that demonstrates the issue (https://stackoverflow.com/help/minimal-reproducible-example) **INCLUDING** all the relevant imports and the code can be copy and pasted **AS IS** to reproduce the issue.
          required: true
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.
        
        Your code should be complete and be able to run by a maintainer **AS IS**.
        
        It should have relevant imports and be as minimal as possible.
        
        If a maintainer can copy it, run it, and see it right away, there's a much higher chance that you'll be able to get help.
        
        **Important!** 
        
        * Reduce your code to the minimum required to reproduce the issue if possible. This makes it much easier for others to help you.
        * Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        from langgraph.graph import StateGraph

        def bad_code(inputs) -> int:
          raise NotImplementedError('For demo purpose')
          
        chain = StateGraph(list)
        chain.invoke('Hello!')
      render: python
  - type: textarea
    id: error
    validations:
      required: false
    attributes:
      label: Error Message and Stack Trace (if applicable)
      description: |
        If you are reporting an error, please include the full error message and stack trace.
      placeholder: |
        Exception + full stack trace
      render: shell
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description telling what you are doing, what you expect to happen, and what is currently happening.
      placeholder: |
        * I'm trying to use the `langgraph` library to do X.
        * I expect to see Y.
        * Instead, it does Z.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        python -m langchain_core.sys_info
      placeholder: |
        python -m langchain_core.sys_info
    validations:
      required: true
